### PR TITLE
Add ES256 algorithm

### LINKED ISSUE #18: Support ES256 (feature request)
This algorithm is necessary to authenticate with Community Solid Server account to Node Solid Server, which uses this library and therefore [fails at that task](https://github.com/nodeSolidServer/node-solid-server/issues/1698#issuecomment-1233439791)

It seems that this library already includes placeholders for the algorithm:
https://github.com/nodeSolidServer/jose/blob/main/src/algorithms/index.js#L58
https://github.com/nodeSolidServer/jose/blob/main/src/algorithms/index.js#L113

...they just need to be filled ❤️

### LINKED ISSUE #1698: Can't access a shared private file on NSS with CSS account
Possibly related or identical to #1602 

## Issue

When we

0. create one fresh [account on solidweb.me](https://solidweb.me/grouptest1/profile/card#me) (CSS v5.0.0) and one [account on solidcommunity.net](https://grouptest1.solidcommunity.net/profile/card#me) (NSS v5.7.2),
1. create a [turtle file (it's private, you won't see it!)](https://grouptest1.solidcommunity.net/group-test/document-person-solidweb-me.ttl) on NSS pod with content
    ```ttl
    @prefix : <https://example.com/>.
    :this :is :test.
    ```
0. share the file for reading with [the CSS account](https://solidweb.me/grouptest1/profile/card#me), so the file's [.acl](https://grouptest1.solidcommunity.net/group-test/document-person-solidweb-me.ttl.acl) looks as follows
    ```ttl
    @prefix : <#>.
    @prefix acl: <http://www.w3.org/ns/auth/acl#>.
    @prefix c: </profile/card#>.
    @prefix c0: <https://solidweb.me/grouptest1/profile/card#>.
    
    :ControlReadWrite
        a acl:Authorization;
        acl:accessTo <document-person-solidweb-me.ttl>;
        acl:agent c:me;
        acl:mode acl:Control, acl:Read, acl:Write.
    :Read
        a acl:Authorization;
        acl:accessTo <document-person-solidweb-me.ttl>;
        acl:agent c0:me;
        acl:mode acl:Read.
    ```
0. try to access the file with the CSS account,

The request fails with `500 Internal Server Error` and body `normalizedAlgorithm.importKey is not a function`

## Expected behavior
Person on CSS can access file on NSS pod shared with them

## Conclusion

Fixing this would IMO be a big step towards interoperability of the two Solid Pods

## See also

[context here](https://github.com/mrkvon/developing-distributed-app/blob/main/group-test.md#person-on-solidcommunity-sharing-file-with-person-on-solidwebme)

~~The other way around (sharing file on CSS with NSS account) also fails, this time with 401. I've opened https://github.com/CommunitySolidServer/CommunitySolidServer/issues/1441 in CSS repository to report that.~~ That issue got fixed when i added missing `solid:oidcIssuer` to the NSS test profiles.

### PR DESCRIPTION
**Pull request by mrkvon**
This still needs code formatting, comments and variable renaming, i'll do soon.

In tests, ES256 signatures are non-deterministic, so we had to go around that...

We also want to test whether this fixes https://github.com/nodeSolidServer/node-solid-server/issues/1698 before merging.

Fixes #18

### CODE REVIEW

**Comment by bourgeoa** [comment]
Thank you so much working on that issue.

**Comment by dmitrizagidulin** [comment]
Wait, that doesn't sound quite right (the non-deterministic ES256 signature part).

According to the [IETF JSON Web Token Best Current Practices Section 3.2](https://tools.ietf.org/id/draft-ietf-oauth-jwt-bcp-02.html#rfc.section.3.2) (JWT BCP) it is best practice to produce deterministic ECDSA signatures as defined by [RFC6979](https://datatracker.ietf.org/doc/html/rfc6979) because of the possibility of recovering the private key when non-deterministic ECDSA signatures are used.

The JWT BCP states that:

> ECDSA signatures require a unique random value for every message that is signed. If even just a few bits of the random value are predictable across multiple messages then the security of the signature scheme may be compromised. In the worst case, the private key may be recoverable by an attacker.

> To counter these attacks, JWT libraries SHOULD implement ECDSA using the deterministic approach defined in [RFC6979]. This approach is completely compatible with existing ECDSA verifiers and so can be implemented without new algorithm identifiers being required.

While I think in this case, isomorphic-webcrypto should generate random-enough numbers (no problems with entropy in either the browser or node), so it's fine that ES256 is non deterministic. But still, I'm curious -- is it non-deterministic both in the browser, and on Node? Or just on Node?

**Comment by mrkvon** [comment]
@dmitrizagidulin 
Thank you for the detailed scrutiny.

So, as far as i understand it, the isomorphic-webcrypto library provides a consistent api around the native implementations; and we use those behind the scenes, right? So for NSS it matters to have the deterministic implementation in Node.

I'll compare Node, Chrome/Chromium, and Firefox implementations and report here.

By _deterministic_, i mean: The same data, algorithm, and private key produce the same signature. I assume we mean the same.

**Comment by dmitrizagidulin** [comment]
@mrkvon - hey, thank you for implementing!!
That’s exactly it, yeah, re isomorphic-webcrypto. 

And yeah, i’m just mostly curious what we’re dealing with, in terms of difference in behavior between browser & node. 
If it turns out non-deterministic is all we have, we’ll deal with it. 

Oh, you know what else might be useful, in mocha tests? (we can add this in a later pr) CSS uses the panva jose library, so maybe we can cross-test for compatibility

**Comment by mrkvon** [comment]
My initial tests indicate that _on my system (Arch Linux)_, Node (using the isomorphic-webcrypto), Chromium and Firefox all generate unique signature (for the same private key and data) every time (i.e. non-deterministic).
It's still possible that it's a system-specific behaviour. I don't know what Node, Firefox and Chrome use for their `crypto` implementation behind the scenes.
Or i'm missing something.

~~For the desired compatibility with CSS we need the verification part, so we could also implement just that, and ignore the signing for now.~~ (`importKey` is needed first. not done yet...)

@dmitrizagidulin 
> Oh, you know what else might be useful, in mocha tests? (we can add this in a later pr) CSS uses the panva jose library, so maybe we can cross-test for compatibility

👍🏾 That's a good idea.

For starters i'll just check whether CSS can authenticate to NSS with this change.

**Comment by mrkvon** [comment]
This project could benefit from linter (e.g. eslint) and code formatter (e.g. prettier)...

**Comment by mrkvon** [comment]
We've added `importKey` and vaguely checked that with the new version https://github.com/nodeSolidServer/node-solid-server/issues/1698 gets resolved. We still need to discover which direct dependencies of NSS will have to be updated.

Marking this as ready for review.

**Comment by bourgeoa** [comment]
> We still need to discover which direct dependencies of NSS will have to be updated.

- Here is I hope an exhaust list of the NSS direct and indirect dependencies related with `@solid/jose` /

@solid/oidc-rp (@solid/jose)
@solid/oidc-rs (@solid/jose)

@solid/solid-multi-rp-client (oidc-rp)
@solid/oidc-auth-manager (oidc-rp, oidc-rs, solid-multi-rp-client)
@solid/solid-auth-oidc (@solid/oidc-rp) --> actually v0.3.0 is used in NSS

solid-auth-client (@solid/oidc-rp) --> deprecated no need to update

node- solid-server (@solid/oidc-auth-manager, solid-auth-client, @solid/solid-auth-oidc)

- You can build the needed  dependencies using https://github.com/solidos/solidos lerna project that includes all needed packages and then run a local NSS server.
  - some more information here https://github.com/SolidOS/solidos/wiki/1.-SolidOS-know-how
  - You can also run a multiuser local server  https://github.com/SolidOS/solidos/wiki/4.-NSS-know-how#running-nss-with-multiuser
  
- I shall try to build on my side and see if I can publish testable versions on npm.

**Comment by bourgeoa** [comment]
It is working in the lerna stack build with different CSS webId's from v4 on my server and v5 https://solidweb.me/bourgeoa/
So I merge.

**Pull request merged**
